```{r}
# Visualisierung der Daten

# Installieren der benötigten Pakete
if (!require(rstudioapi)) {
  install.packages("rstudioapi")
  library(rstudioapi) 
}

if (!require(ggplot2)) {
  install.packages("ggplot2")
  library(ggplot2)
}

if (!require(Hmisc)) {
  install.packages("Hmisc")
  library(Hmisc)
}

# Arbeitsspeicher leeren
remove(list = ls())
graphics.off()

# Arbeitsverzeichnis auf das Projektverzeichnis setzen
proj_pfad <- getActiveProject()
setwd(proj_pfad)

# Durchführen des Aufbereitungs-Skripts ("source" führt zum fehlerhaften Durchführen mit Umlauten, daher die explizite Angabe der Unicode-Kodierung)
eval(parse("Aufbereitung.R", encoding = "UTF-8"))

# Definieren einer Funktion zum Erstellen von einfachen Barplots: Es müssen die Daten und die Spaltennamen der Variablen,
# die auf der X-Achse und der Y-Achse abgetragen werden sollen übergeben werden (alternativ können auch die Indizes der
# Spalten übergeben werden, dann sollten allerdings die Achsenbeschriftungen zusätzlich angepasst werden). Zusätzlich
# können einige kosmetische Aspekte angepasst werden.
custom_plot <- function(data,
                     x,
                     y,
                     geom = "bar",
                     xLabel = x,
                     yLabel = y,
                     barWidth = .7,
                     fill = "#005b96") {
  ggplot(data, aes(x = data[ ,x], y = data[ ,y])) +
    stat_summary(fun.y = mean,
                 geom = geom,
                 width = barWidth,
                 fill = fill) +
    stat_summary(fun.data = mean_cl_normal,
                 geom = "errorbar",
                 width = barWidth/2.5) +
    # Beschriftung der Achsen anpassen
    xlab(xLabel)+
    ylab(yLabel) +
    # Platzieren der Balken direkt auf der X-Achse (und etwas entfernt von der Y-Achse)
    scale_y_continuous(expand = c(0, 0, 0.05, 0)) +
    # Enfernen des Hintergrunds und Einzeichnen schwarzer Achsen
    theme_classic() +
    # Entfernen der Ticks an der X-Achse
    theme(axis.ticks.x = element_blank())
}

```

```{r}

# Umsatz in Abhängigkeit von der Warengruppe
custom_plot(daten, "Warengruppe", "Umsatz")

```


```{r}

# Umsatz in Abhängigkeit von der Temperatur
with(daten, plot(Temperatur, Umsatz))

```



```{r}

# Umsatz in Abhängigkeit von der Bewölkung
custom_plot(daten, "Bewoelkung", "Umsatz", xLabel = "Bewölkung", geom = "line")

```



```{r}

# Umsatz in Abhängigkeit von der WIndgeschwindigkeit
custom_plot(daten, "Windgeschwindigkeit", "Umsatz", geom = "line")

```

```{r}

# Umsatz in Abhängigkeit von der WIndgeschwindigkeit
custom_plot(daten, "Wettercode", "Umsatz")

```

```{r}

# Umsatz in Abhängigkeit vom Wochentag
custom_plot(daten, "Wochentag", "Umsatz")

```

```{r}

# Umsatz in Abhängigkeit von der Kieler Woche
custom_plot(daten, "KielerWoche", "Umsatz", xLabel = "Kieler Woche")

```

```{r}

# Umsatz in Abhängigkeit von der Zeit im Monat
custom_plot(daten, "Zeit_Im_Monat", "Umsatz", xLabel = "Zeit im Monat")

```

```{r}

# Umsatz in Abhängigkeit von der Zeit im Monat
custom_plot(daten, "Jahrzeiten", "Umsatz", xLabel = "Jahreszeit")

```


```{r}

# Umsatz in Abhängigkeit von der Zeit im Monat
custom_plot(daten, "Feiertag", "Umsatz")

```

```{r}

# Umsatz in Abhängigkeit von der Zeit im Monat
custom_plot(daten, "Feiertag_in_weniger_als_1_Tagen", "Umsatz")

```


```{r}

# Umsatz in Abhängigkeit von der Zeit im Monat
custom_plot(daten, "Feiertag_in_weniger_als_2_Tagen", "Umsatz")

```


```{r}

# Umsatz in Abhängigkeit von der Zeit im Monat
custom_plot(daten, "Feiertag_in_weniger_als_3_Tagen", "Umsatz")

```


```{r}

# Umsatz in Abhängigkeit von der Zeit im Monat
custom_plot(daten, "Feiertag_vor_weniger_als_1_Tagen", "Umsatz")

```


```{r}

# Umsatz in Abhängigkeit von der Zeit im Monat
custom_plot(daten, "Feiertag_vor_weniger_als_2_Tagen", "Umsatz")

```


```{r}

# Umsatz in Abhängigkeit von der Zeit im Monat
custom_plot(daten, "Feiertag_vor_weniger_als_3_Tagen", "Umsatz")

```